### PR TITLE
Redesign dockerfile

### PR DESCRIPTION
**Pull request by Security-Chief-Odo**
Builds the python image first with requirements and initializes the CLIP model. Entrypoint then only needs to load them from the containerfile and proceed; creates a faster starting container.

### CODE REVIEW

**Comment by poVoq** [comment]
It shouldn't only load the pictrs version. The old docker-file intentionally left that open to the person running the container.

Also: is there a to dynamically load the clip model and store it in a volume so that you don't need to download 2.3GB container-files on each update?

**Comment by Security-Chief-Odo** [comment]
Yeah I was trying to make that latter part happen but in the context of what I need, that download on startup takes a longer time. I wanted an image ready to go; in this case its started and listening within 5s, instead of 200s.

**Comment by poVoq** [comment]
Indeed that is a bit confusing on container start. But one could put it in the instructions to manually download the clip model and store it somewhere for access via the container, and the container could just check if it is up to date?

**Comment by Security-Chief-Odo** [comment]
> Indeed that is a bit confusing on container start. But one could put it in the instructions to manually download the clip model and store it somewhere for access via the container, and the container could just check if it is up to date?

Yeah I'll work on that method instead, makes sense.

**Comment by poVoq** [comment]
The LibreTranslate container does that, but on slow connections this means the container doesn't start for 30 minutes or so, with little feedback why it isn't starting, causing many people to think it is broken.

**Comment by db0** [comment]
We can easily add a log about that. It would be easier than to ask everyone to download the model manually.

**Pull request closed without merging**
